services:
  - name: booking-laravel
    type: web
    env: docker
    repo: https://github.com/Asaf53/Asaf53-booking-laravel-bc10
    plan: free
    branch: main
    region: frankfurt
    healthCheckPath: /api/health
    autoDeploy: true
    postdeploy: 
      - php artisan migrate --force
      - php artisan db:seed --class=roles
      - php artisan db:seed --class=country_city
      - php artisan db:seed --class=User
